language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "TCV4ezBvKpGHKpk5ACThEmWdFAeUd5uLFwxbyOGuCb/w+jYwerj0VbXRBtAIft+hYeAMkQexb+867RaKj7fPOFtOdw8z80VWGDLZDZK5OmYFiq7huVIES8UFptZlriEcru/As5jL1kHa3Kyd0Na7EvziNYjO8f0ZmdDEMk9I4Q/6WCsbtCduPvU4psyLC4f+fI3ZeGvUkU+ycZTkllP/P9io1yEop26fU76uS6K9+WHXeI9Vj2A9Zztx/Gwv0ia0ytVkKjdLk6jPY9K0nPRJMJnklX7qNM6pVDOJ6U+oxuxlwTXdJIMUhqBFWSz0OotK0zdkdKc1f0lWsEmh/K0tVo885CFX/XfK1ESEXUARP5WzZoWGvomvNUQOuFPY6kqJY9bwiYiUNxAnzRQCLFDgO1cFO1UVtPuxehirrEfb9qSxjj0MtwsXKTVjMrPkUdwOqZZr8ckoB/QGKmRNmbeLq1UF238ApJPLV0rl/NWPaQgWSnzl2D1NZKo2GtsSOP5ykjzWan+yQe0iWFEd3n5yubx6E2lzHnGHLBEUH569kzJrKL7sKMhYUxhthX2tqoCIH7K2X2jjT4DO+hPZsLePs757lF+vwWeWs0lNDVhPJpIZ3Yxqu9N5+K5ToFGnDeKv3B+RhAPxe6c2DiRCczrwsp3fhvicwtD9YLQXFSEii9U="